### ISSUE TITLE
Calorie Tracker

### ISSUE THREAD

**Issue by bqrichards** [bqrichards/alpha#1]
- [ ] Enter food eaten attached to the day
- [ ] Mark calories for food items
- [ ] Set calorie target
- [ ] View other day’s food
